name: grafu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_modular: ^5.0.3
  google_maps: ^6.2.0
  google_maps_flutter: ^2.1.10
  google_maps_flutter_web: ^0.4.0+1
  image_cropper: ^2.0.3
  image_cropper_for_web: ^0.0.4
  image_picker: ^0.8.5+3
  rename: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  storybook_flutter: ^0.11.1
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
