name: grafu
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.4.0
  built_value_generator: ^8.4.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.3
  flutter_secure_storage: ^6.0.0
  flutter_staggered_grid_view: ^0.6.2
  google_maps: ^6.2.0
  google_maps_flutter: ^2.1.10
  google_maps_flutter_web: ^0.4.0+1
  google_sign_in: ^5.4.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  mobx: ^2.0.7+5
  mobx_codegen: ^2.0.7
  photo_view: ^0.14.0
  provider: ^6.0.3
  rename: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  storybook_flutter: ^0.11.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
